// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pkg/proto/request.proto

package com.proto.gruler;

public final class RequestOuterClass {
  private RequestOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Request)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.proto.HttpRequest httpRequest = 1;</code>
     */
    boolean hasHttpRequest();
    /**
     * <code>.proto.HttpRequest httpRequest = 1;</code>
     */
    com.proto.gruler.RequestOuterClass.HttpRequest getHttpRequest();
    /**
     * <code>.proto.HttpRequest httpRequest = 1;</code>
     */
    com.proto.gruler.RequestOuterClass.HttpRequestOrBuilder getHttpRequestOrBuilder();
  }
  /**
   * Protobuf type {@code proto.Request}
   */
  public  static final class Request extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Request)
      RequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Request.newBuilder() to construct.
    private Request(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Request() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Request(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.proto.gruler.RequestOuterClass.HttpRequest.Builder subBuilder = null;
              if (httpRequest_ != null) {
                subBuilder = httpRequest_.toBuilder();
              }
              httpRequest_ = input.readMessage(com.proto.gruler.RequestOuterClass.HttpRequest.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(httpRequest_);
                httpRequest_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.gruler.RequestOuterClass.internal_static_proto_Request_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.gruler.RequestOuterClass.internal_static_proto_Request_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.gruler.RequestOuterClass.Request.class, com.proto.gruler.RequestOuterClass.Request.Builder.class);
    }

    public static final int HTTPREQUEST_FIELD_NUMBER = 1;
    private com.proto.gruler.RequestOuterClass.HttpRequest httpRequest_;
    /**
     * <code>.proto.HttpRequest httpRequest = 1;</code>
     */
    public boolean hasHttpRequest() {
      return httpRequest_ != null;
    }
    /**
     * <code>.proto.HttpRequest httpRequest = 1;</code>
     */
    public com.proto.gruler.RequestOuterClass.HttpRequest getHttpRequest() {
      return httpRequest_ == null ? com.proto.gruler.RequestOuterClass.HttpRequest.getDefaultInstance() : httpRequest_;
    }
    /**
     * <code>.proto.HttpRequest httpRequest = 1;</code>
     */
    public com.proto.gruler.RequestOuterClass.HttpRequestOrBuilder getHttpRequestOrBuilder() {
      return getHttpRequest();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (httpRequest_ != null) {
        output.writeMessage(1, getHttpRequest());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (httpRequest_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHttpRequest());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.gruler.RequestOuterClass.Request)) {
        return super.equals(obj);
      }
      com.proto.gruler.RequestOuterClass.Request other = (com.proto.gruler.RequestOuterClass.Request) obj;

      boolean result = true;
      result = result && (hasHttpRequest() == other.hasHttpRequest());
      if (hasHttpRequest()) {
        result = result && getHttpRequest()
            .equals(other.getHttpRequest());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasHttpRequest()) {
        hash = (37 * hash) + HTTPREQUEST_FIELD_NUMBER;
        hash = (53 * hash) + getHttpRequest().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.gruler.RequestOuterClass.Request parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.gruler.RequestOuterClass.Request parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.gruler.RequestOuterClass.Request prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Request}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Request)
        com.proto.gruler.RequestOuterClass.RequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.gruler.RequestOuterClass.internal_static_proto_Request_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.gruler.RequestOuterClass.internal_static_proto_Request_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.gruler.RequestOuterClass.Request.class, com.proto.gruler.RequestOuterClass.Request.Builder.class);
      }

      // Construct using com.proto.gruler.RequestOuterClass.Request.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (httpRequestBuilder_ == null) {
          httpRequest_ = null;
        } else {
          httpRequest_ = null;
          httpRequestBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.gruler.RequestOuterClass.internal_static_proto_Request_descriptor;
      }

      @java.lang.Override
      public com.proto.gruler.RequestOuterClass.Request getDefaultInstanceForType() {
        return com.proto.gruler.RequestOuterClass.Request.getDefaultInstance();
      }

      @java.lang.Override
      public com.proto.gruler.RequestOuterClass.Request build() {
        com.proto.gruler.RequestOuterClass.Request result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.proto.gruler.RequestOuterClass.Request buildPartial() {
        com.proto.gruler.RequestOuterClass.Request result = new com.proto.gruler.RequestOuterClass.Request(this);
        if (httpRequestBuilder_ == null) {
          result.httpRequest_ = httpRequest_;
        } else {
          result.httpRequest_ = httpRequestBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.gruler.RequestOuterClass.Request) {
          return mergeFrom((com.proto.gruler.RequestOuterClass.Request)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.gruler.RequestOuterClass.Request other) {
        if (other == com.proto.gruler.RequestOuterClass.Request.getDefaultInstance()) return this;
        if (other.hasHttpRequest()) {
          mergeHttpRequest(other.getHttpRequest());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.gruler.RequestOuterClass.Request parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.gruler.RequestOuterClass.Request) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.proto.gruler.RequestOuterClass.HttpRequest httpRequest_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.proto.gruler.RequestOuterClass.HttpRequest, com.proto.gruler.RequestOuterClass.HttpRequest.Builder, com.proto.gruler.RequestOuterClass.HttpRequestOrBuilder> httpRequestBuilder_;
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      public boolean hasHttpRequest() {
        return httpRequestBuilder_ != null || httpRequest_ != null;
      }
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      public com.proto.gruler.RequestOuterClass.HttpRequest getHttpRequest() {
        if (httpRequestBuilder_ == null) {
          return httpRequest_ == null ? com.proto.gruler.RequestOuterClass.HttpRequest.getDefaultInstance() : httpRequest_;
        } else {
          return httpRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      public Builder setHttpRequest(com.proto.gruler.RequestOuterClass.HttpRequest value) {
        if (httpRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          httpRequest_ = value;
          onChanged();
        } else {
          httpRequestBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      public Builder setHttpRequest(
          com.proto.gruler.RequestOuterClass.HttpRequest.Builder builderForValue) {
        if (httpRequestBuilder_ == null) {
          httpRequest_ = builderForValue.build();
          onChanged();
        } else {
          httpRequestBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      public Builder mergeHttpRequest(com.proto.gruler.RequestOuterClass.HttpRequest value) {
        if (httpRequestBuilder_ == null) {
          if (httpRequest_ != null) {
            httpRequest_ =
              com.proto.gruler.RequestOuterClass.HttpRequest.newBuilder(httpRequest_).mergeFrom(value).buildPartial();
          } else {
            httpRequest_ = value;
          }
          onChanged();
        } else {
          httpRequestBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      public Builder clearHttpRequest() {
        if (httpRequestBuilder_ == null) {
          httpRequest_ = null;
          onChanged();
        } else {
          httpRequest_ = null;
          httpRequestBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      public com.proto.gruler.RequestOuterClass.HttpRequest.Builder getHttpRequestBuilder() {
        
        onChanged();
        return getHttpRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      public com.proto.gruler.RequestOuterClass.HttpRequestOrBuilder getHttpRequestOrBuilder() {
        if (httpRequestBuilder_ != null) {
          return httpRequestBuilder_.getMessageOrBuilder();
        } else {
          return httpRequest_ == null ?
              com.proto.gruler.RequestOuterClass.HttpRequest.getDefaultInstance() : httpRequest_;
        }
      }
      /**
       * <code>.proto.HttpRequest httpRequest = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.proto.gruler.RequestOuterClass.HttpRequest, com.proto.gruler.RequestOuterClass.HttpRequest.Builder, com.proto.gruler.RequestOuterClass.HttpRequestOrBuilder> 
          getHttpRequestFieldBuilder() {
        if (httpRequestBuilder_ == null) {
          httpRequestBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.proto.gruler.RequestOuterClass.HttpRequest, com.proto.gruler.RequestOuterClass.HttpRequest.Builder, com.proto.gruler.RequestOuterClass.HttpRequestOrBuilder>(
                  getHttpRequest(),
                  getParentForChildren(),
                  isClean());
          httpRequest_ = null;
        }
        return httpRequestBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Request)
    }

    // @@protoc_insertion_point(class_scope:proto.Request)
    private static final com.proto.gruler.RequestOuterClass.Request DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.gruler.RequestOuterClass.Request();
    }

    public static com.proto.gruler.RequestOuterClass.Request getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Request>
        PARSER = new com.google.protobuf.AbstractParser<Request>() {
      @java.lang.Override
      public Request parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Request(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Request> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Request> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.proto.gruler.RequestOuterClass.Request getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HttpRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.HttpRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string method = 1;</code>
     */
    java.lang.String getMethod();
    /**
     * <code>string method = 1;</code>
     */
    com.google.protobuf.ByteString
        getMethodBytes();

    /**
     * <code>string requestUri = 2;</code>
     */
    java.lang.String getRequestUri();
    /**
     * <code>string requestUri = 2;</code>
     */
    com.google.protobuf.ByteString
        getRequestUriBytes();

    /**
     * <code>string httpVersion = 3;</code>
     */
    java.lang.String getHttpVersion();
    /**
     * <code>string httpVersion = 3;</code>
     */
    com.google.protobuf.ByteString
        getHttpVersionBytes();

    /**
     * <code>string clientIp = 4;</code>
     */
    java.lang.String getClientIp();
    /**
     * <code>string clientIp = 4;</code>
     */
    com.google.protobuf.ByteString
        getClientIpBytes();

    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    int getHeadersCount();
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    boolean containsHeaders(
        java.lang.String key);
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    java.util.Map<java.lang.String, java.lang.String>
    getHeaders();
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getHeadersMap();
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */

    java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue);
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */

    java.lang.String getHeadersOrThrow(
        java.lang.String key);
  }
  /**
   * Protobuf type {@code proto.HttpRequest}
   */
  public  static final class HttpRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.HttpRequest)
      HttpRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HttpRequest.newBuilder() to construct.
    private HttpRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HttpRequest() {
      method_ = "";
      requestUri_ = "";
      httpVersion_ = "";
      clientIp_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HttpRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              method_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              requestUri_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              httpVersion_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              clientIp_ = s;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                headers_ = com.google.protobuf.MapField.newMapField(
                    HeadersDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000010;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              headers__ = input.readMessage(
                  HeadersDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              headers_.getMutableMap().put(
                  headers__.getKey(), headers__.getValue());
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.gruler.RequestOuterClass.internal_static_proto_HttpRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @java.lang.Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 5:
          return internalGetHeaders();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.gruler.RequestOuterClass.internal_static_proto_HttpRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.gruler.RequestOuterClass.HttpRequest.class, com.proto.gruler.RequestOuterClass.HttpRequest.Builder.class);
    }

    private int bitField0_;
    public static final int METHOD_FIELD_NUMBER = 1;
    private volatile java.lang.Object method_;
    /**
     * <code>string method = 1;</code>
     */
    public java.lang.String getMethod() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        method_ = s;
        return s;
      }
    }
    /**
     * <code>string method = 1;</code>
     */
    public com.google.protobuf.ByteString
        getMethodBytes() {
      java.lang.Object ref = method_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        method_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int REQUESTURI_FIELD_NUMBER = 2;
    private volatile java.lang.Object requestUri_;
    /**
     * <code>string requestUri = 2;</code>
     */
    public java.lang.String getRequestUri() {
      java.lang.Object ref = requestUri_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        requestUri_ = s;
        return s;
      }
    }
    /**
     * <code>string requestUri = 2;</code>
     */
    public com.google.protobuf.ByteString
        getRequestUriBytes() {
      java.lang.Object ref = requestUri_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        requestUri_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HTTPVERSION_FIELD_NUMBER = 3;
    private volatile java.lang.Object httpVersion_;
    /**
     * <code>string httpVersion = 3;</code>
     */
    public java.lang.String getHttpVersion() {
      java.lang.Object ref = httpVersion_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        httpVersion_ = s;
        return s;
      }
    }
    /**
     * <code>string httpVersion = 3;</code>
     */
    public com.google.protobuf.ByteString
        getHttpVersionBytes() {
      java.lang.Object ref = httpVersion_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        httpVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENTIP_FIELD_NUMBER = 4;
    private volatile java.lang.Object clientIp_;
    /**
     * <code>string clientIp = 4;</code>
     */
    public java.lang.String getClientIp() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientIp_ = s;
        return s;
      }
    }
    /**
     * <code>string clientIp = 4;</code>
     */
    public com.google.protobuf.ByteString
        getClientIpBytes() {
      java.lang.Object ref = clientIp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientIp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADERS_FIELD_NUMBER = 5;
    private static final class HeadersDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  com.proto.gruler.RequestOuterClass.internal_static_proto_HttpRequest_HeadersEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> headers_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetHeaders() {
      if (headers_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            HeadersDefaultEntryHolder.defaultEntry);
      }
      return headers_;
    }

    public int getHeadersCount() {
      return internalGetHeaders().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */

    public boolean containsHeaders(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      return internalGetHeaders().getMap().containsKey(key);
    }
    /**
     * Use {@link #getHeadersMap()} instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
      return getHeadersMap();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
      return internalGetHeaders().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */

    public java.lang.String getHeadersOrDefault(
        java.lang.String key,
        java.lang.String defaultValue) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; headers = 5;</code>
     */

    public java.lang.String getHeadersOrThrow(
        java.lang.String key) {
      if (key == null) { throw new java.lang.NullPointerException(); }
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetHeaders().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getMethodBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, method_);
      }
      if (!getRequestUriBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, requestUri_);
      }
      if (!getHttpVersionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, httpVersion_);
      }
      if (!getClientIpBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, clientIp_);
      }
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetHeaders(),
          HeadersDefaultEntryHolder.defaultEntry,
          5);
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getMethodBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, method_);
      }
      if (!getRequestUriBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, requestUri_);
      }
      if (!getHttpVersionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, httpVersion_);
      }
      if (!getClientIpBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, clientIp_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetHeaders().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        headers__ = HeadersDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(5, headers__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.gruler.RequestOuterClass.HttpRequest)) {
        return super.equals(obj);
      }
      com.proto.gruler.RequestOuterClass.HttpRequest other = (com.proto.gruler.RequestOuterClass.HttpRequest) obj;

      boolean result = true;
      result = result && getMethod()
          .equals(other.getMethod());
      result = result && getRequestUri()
          .equals(other.getRequestUri());
      result = result && getHttpVersion()
          .equals(other.getHttpVersion());
      result = result && getClientIp()
          .equals(other.getClientIp());
      result = result && internalGetHeaders().equals(
          other.internalGetHeaders());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + METHOD_FIELD_NUMBER;
      hash = (53 * hash) + getMethod().hashCode();
      hash = (37 * hash) + REQUESTURI_FIELD_NUMBER;
      hash = (53 * hash) + getRequestUri().hashCode();
      hash = (37 * hash) + HTTPVERSION_FIELD_NUMBER;
      hash = (53 * hash) + getHttpVersion().hashCode();
      hash = (37 * hash) + CLIENTIP_FIELD_NUMBER;
      hash = (53 * hash) + getClientIp().hashCode();
      if (!internalGetHeaders().getMap().isEmpty()) {
        hash = (37 * hash) + HEADERS_FIELD_NUMBER;
        hash = (53 * hash) + internalGetHeaders().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.gruler.RequestOuterClass.HttpRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.gruler.RequestOuterClass.HttpRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.HttpRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.HttpRequest)
        com.proto.gruler.RequestOuterClass.HttpRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.gruler.RequestOuterClass.internal_static_proto_HttpRequest_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetHeaders();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 5:
            return internalGetMutableHeaders();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.gruler.RequestOuterClass.internal_static_proto_HttpRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.gruler.RequestOuterClass.HttpRequest.class, com.proto.gruler.RequestOuterClass.HttpRequest.Builder.class);
      }

      // Construct using com.proto.gruler.RequestOuterClass.HttpRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        method_ = "";

        requestUri_ = "";

        httpVersion_ = "";

        clientIp_ = "";

        internalGetMutableHeaders().clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.gruler.RequestOuterClass.internal_static_proto_HttpRequest_descriptor;
      }

      @java.lang.Override
      public com.proto.gruler.RequestOuterClass.HttpRequest getDefaultInstanceForType() {
        return com.proto.gruler.RequestOuterClass.HttpRequest.getDefaultInstance();
      }

      @java.lang.Override
      public com.proto.gruler.RequestOuterClass.HttpRequest build() {
        com.proto.gruler.RequestOuterClass.HttpRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.proto.gruler.RequestOuterClass.HttpRequest buildPartial() {
        com.proto.gruler.RequestOuterClass.HttpRequest result = new com.proto.gruler.RequestOuterClass.HttpRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.method_ = method_;
        result.requestUri_ = requestUri_;
        result.httpVersion_ = httpVersion_;
        result.clientIp_ = clientIp_;
        result.headers_ = internalGetHeaders();
        result.headers_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.gruler.RequestOuterClass.HttpRequest) {
          return mergeFrom((com.proto.gruler.RequestOuterClass.HttpRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.gruler.RequestOuterClass.HttpRequest other) {
        if (other == com.proto.gruler.RequestOuterClass.HttpRequest.getDefaultInstance()) return this;
        if (!other.getMethod().isEmpty()) {
          method_ = other.method_;
          onChanged();
        }
        if (!other.getRequestUri().isEmpty()) {
          requestUri_ = other.requestUri_;
          onChanged();
        }
        if (!other.getHttpVersion().isEmpty()) {
          httpVersion_ = other.httpVersion_;
          onChanged();
        }
        if (!other.getClientIp().isEmpty()) {
          clientIp_ = other.clientIp_;
          onChanged();
        }
        internalGetMutableHeaders().mergeFrom(
            other.internalGetHeaders());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.gruler.RequestOuterClass.HttpRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.gruler.RequestOuterClass.HttpRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object method_ = "";
      /**
       * <code>string method = 1;</code>
       */
      public java.lang.String getMethod() {
        java.lang.Object ref = method_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          method_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string method = 1;</code>
       */
      public com.google.protobuf.ByteString
          getMethodBytes() {
        java.lang.Object ref = method_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          method_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string method = 1;</code>
       */
      public Builder setMethod(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        method_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string method = 1;</code>
       */
      public Builder clearMethod() {
        
        method_ = getDefaultInstance().getMethod();
        onChanged();
        return this;
      }
      /**
       * <code>string method = 1;</code>
       */
      public Builder setMethodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        method_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object requestUri_ = "";
      /**
       * <code>string requestUri = 2;</code>
       */
      public java.lang.String getRequestUri() {
        java.lang.Object ref = requestUri_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          requestUri_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string requestUri = 2;</code>
       */
      public com.google.protobuf.ByteString
          getRequestUriBytes() {
        java.lang.Object ref = requestUri_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          requestUri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string requestUri = 2;</code>
       */
      public Builder setRequestUri(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        requestUri_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string requestUri = 2;</code>
       */
      public Builder clearRequestUri() {
        
        requestUri_ = getDefaultInstance().getRequestUri();
        onChanged();
        return this;
      }
      /**
       * <code>string requestUri = 2;</code>
       */
      public Builder setRequestUriBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        requestUri_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object httpVersion_ = "";
      /**
       * <code>string httpVersion = 3;</code>
       */
      public java.lang.String getHttpVersion() {
        java.lang.Object ref = httpVersion_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          httpVersion_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string httpVersion = 3;</code>
       */
      public com.google.protobuf.ByteString
          getHttpVersionBytes() {
        java.lang.Object ref = httpVersion_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          httpVersion_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string httpVersion = 3;</code>
       */
      public Builder setHttpVersion(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        httpVersion_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string httpVersion = 3;</code>
       */
      public Builder clearHttpVersion() {
        
        httpVersion_ = getDefaultInstance().getHttpVersion();
        onChanged();
        return this;
      }
      /**
       * <code>string httpVersion = 3;</code>
       */
      public Builder setHttpVersionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        httpVersion_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientIp_ = "";
      /**
       * <code>string clientIp = 4;</code>
       */
      public java.lang.String getClientIp() {
        java.lang.Object ref = clientIp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientIp_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string clientIp = 4;</code>
       */
      public com.google.protobuf.ByteString
          getClientIpBytes() {
        java.lang.Object ref = clientIp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientIp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string clientIp = 4;</code>
       */
      public Builder setClientIp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientIp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string clientIp = 4;</code>
       */
      public Builder clearClientIp() {
        
        clientIp_ = getDefaultInstance().getClientIp();
        onChanged();
        return this;
      }
      /**
       * <code>string clientIp = 4;</code>
       */
      public Builder setClientIpBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientIp_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> headers_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetHeaders() {
        if (headers_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              HeadersDefaultEntryHolder.defaultEntry);
        }
        return headers_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableHeaders() {
        onChanged();;
        if (headers_ == null) {
          headers_ = com.google.protobuf.MapField.newMapField(
              HeadersDefaultEntryHolder.defaultEntry);
        }
        if (!headers_.isMutable()) {
          headers_ = headers_.copy();
        }
        return headers_;
      }

      public int getHeadersCount() {
        return internalGetHeaders().getMap().size();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */

      public boolean containsHeaders(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        return internalGetHeaders().getMap().containsKey(key);
      }
      /**
       * Use {@link #getHeadersMap()} instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String> getHeaders() {
        return getHeadersMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */

      public java.util.Map<java.lang.String, java.lang.String> getHeadersMap() {
        return internalGetHeaders().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */

      public java.lang.String getHeadersOrDefault(
          java.lang.String key,
          java.lang.String defaultValue) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetHeaders().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */

      public java.lang.String getHeadersOrThrow(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        java.util.Map<java.lang.String, java.lang.String> map =
            internalGetHeaders().getMap();
        if (!map.containsKey(key)) {
          throw new java.lang.IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearHeaders() {
        internalGetMutableHeaders().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */

      public Builder removeHeaders(
          java.lang.String key) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableHeaders().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @java.lang.Deprecated
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableHeaders() {
        return internalGetMutableHeaders().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */
      public Builder putHeaders(
          java.lang.String key,
          java.lang.String value) {
        if (key == null) { throw new java.lang.NullPointerException(); }
        if (value == null) { throw new java.lang.NullPointerException(); }
        internalGetMutableHeaders().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, string&gt; headers = 5;</code>
       */

      public Builder putAllHeaders(
          java.util.Map<java.lang.String, java.lang.String> values) {
        internalGetMutableHeaders().getMutableMap()
            .putAll(values);
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.HttpRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.HttpRequest)
    private static final com.proto.gruler.RequestOuterClass.HttpRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.gruler.RequestOuterClass.HttpRequest();
    }

    public static com.proto.gruler.RequestOuterClass.HttpRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HttpRequest>
        PARSER = new com.google.protobuf.AbstractParser<HttpRequest>() {
      @java.lang.Override
      public HttpRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HttpRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HttpRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HttpRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.proto.gruler.RequestOuterClass.HttpRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Request_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Request_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HttpRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HttpRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_HttpRequest_HeadersEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_HttpRequest_HeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027pkg/proto/request.proto\022\005proto\"2\n\007Requ" +
      "est\022\'\n\013httpRequest\030\001 \001(\0132\022.proto.HttpReq" +
      "uest\"\272\001\n\013HttpRequest\022\016\n\006method\030\001 \001(\t\022\022\n\n" +
      "requestUri\030\002 \001(\t\022\023\n\013httpVersion\030\003 \001(\t\022\020\n" +
      "\010clientIp\030\004 \001(\t\0220\n\007headers\030\005 \003(\0132\037.proto" +
      ".HttpRequest.HeadersEntry\032.\n\014HeadersEntr" +
      "y\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B$\n\020com" +
      ".proto.grulerZ\020gruler/pkg/protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Request_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Request_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Request_descriptor,
        new java.lang.String[] { "HttpRequest", });
    internal_static_proto_HttpRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_HttpRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HttpRequest_descriptor,
        new java.lang.String[] { "Method", "RequestUri", "HttpVersion", "ClientIp", "Headers", });
    internal_static_proto_HttpRequest_HeadersEntry_descriptor =
      internal_static_proto_HttpRequest_descriptor.getNestedTypes().get(0);
    internal_static_proto_HttpRequest_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_HttpRequest_HeadersEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
