// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pkg/proto/response.proto

package com.proto.gruler;

public final class ResponseOuterClass {
  private ResponseOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 executionTime = 1;</code>
     * @return The executionTime.
     */
    long getExecutionTime();

    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    java.util.List<com.proto.gruler.ResponseOuterClass.Action> 
        getActionsList();
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    com.proto.gruler.ResponseOuterClass.Action getActions(int index);
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    int getActionsCount();
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    java.util.List<? extends com.proto.gruler.ResponseOuterClass.ActionOrBuilder> 
        getActionsOrBuilderList();
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    com.proto.gruler.ResponseOuterClass.ActionOrBuilder getActionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code proto.Response}
   */
  public static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
      actions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              executionTime_ = input.readInt64();
              break;
            }
            case 16: {

              success_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                actions_ = new java.util.ArrayList<com.proto.gruler.ResponseOuterClass.Action>();
                mutable_bitField0_ |= 0x00000001;
              }
              actions_.add(
                  input.readMessage(com.proto.gruler.ResponseOuterClass.Action.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          actions_ = java.util.Collections.unmodifiableList(actions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.gruler.ResponseOuterClass.internal_static_proto_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.gruler.ResponseOuterClass.internal_static_proto_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.gruler.ResponseOuterClass.Response.class, com.proto.gruler.ResponseOuterClass.Response.Builder.class);
    }

    public static final int EXECUTIONTIME_FIELD_NUMBER = 1;
    private long executionTime_;
    /**
     * <code>int64 executionTime = 1;</code>
     * @return The executionTime.
     */
    @java.lang.Override
    public long getExecutionTime() {
      return executionTime_;
    }

    public static final int SUCCESS_FIELD_NUMBER = 2;
    private boolean success_;
    /**
     * <code>bool success = 2;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }

    public static final int ACTIONS_FIELD_NUMBER = 3;
    private java.util.List<com.proto.gruler.ResponseOuterClass.Action> actions_;
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    @java.lang.Override
    public java.util.List<com.proto.gruler.ResponseOuterClass.Action> getActionsList() {
      return actions_;
    }
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.proto.gruler.ResponseOuterClass.ActionOrBuilder> 
        getActionsOrBuilderList() {
      return actions_;
    }
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    @java.lang.Override
    public int getActionsCount() {
      return actions_.size();
    }
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    @java.lang.Override
    public com.proto.gruler.ResponseOuterClass.Action getActions(int index) {
      return actions_.get(index);
    }
    /**
     * <code>repeated .proto.Action actions = 3;</code>
     */
    @java.lang.Override
    public com.proto.gruler.ResponseOuterClass.ActionOrBuilder getActionsOrBuilder(
        int index) {
      return actions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (executionTime_ != 0L) {
        output.writeInt64(1, executionTime_);
      }
      if (success_ != false) {
        output.writeBool(2, success_);
      }
      for (int i = 0; i < actions_.size(); i++) {
        output.writeMessage(3, actions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (executionTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, executionTime_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, success_);
      }
      for (int i = 0; i < actions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, actions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.gruler.ResponseOuterClass.Response)) {
        return super.equals(obj);
      }
      com.proto.gruler.ResponseOuterClass.Response other = (com.proto.gruler.ResponseOuterClass.Response) obj;

      if (getExecutionTime()
          != other.getExecutionTime()) return false;
      if (getSuccess()
          != other.getSuccess()) return false;
      if (!getActionsList()
          .equals(other.getActionsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EXECUTIONTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getExecutionTime());
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      if (getActionsCount() > 0) {
        hash = (37 * hash) + ACTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getActionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.gruler.ResponseOuterClass.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.gruler.ResponseOuterClass.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Response)
        com.proto.gruler.ResponseOuterClass.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.gruler.ResponseOuterClass.internal_static_proto_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.gruler.ResponseOuterClass.internal_static_proto_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.gruler.ResponseOuterClass.Response.class, com.proto.gruler.ResponseOuterClass.Response.Builder.class);
      }

      // Construct using com.proto.gruler.ResponseOuterClass.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getActionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        executionTime_ = 0L;

        success_ = false;

        if (actionsBuilder_ == null) {
          actions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          actionsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.gruler.ResponseOuterClass.internal_static_proto_Response_descriptor;
      }

      @java.lang.Override
      public com.proto.gruler.ResponseOuterClass.Response getDefaultInstanceForType() {
        return com.proto.gruler.ResponseOuterClass.Response.getDefaultInstance();
      }

      @java.lang.Override
      public com.proto.gruler.ResponseOuterClass.Response build() {
        com.proto.gruler.ResponseOuterClass.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.proto.gruler.ResponseOuterClass.Response buildPartial() {
        com.proto.gruler.ResponseOuterClass.Response result = new com.proto.gruler.ResponseOuterClass.Response(this);
        int from_bitField0_ = bitField0_;
        result.executionTime_ = executionTime_;
        result.success_ = success_;
        if (actionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            actions_ = java.util.Collections.unmodifiableList(actions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.actions_ = actions_;
        } else {
          result.actions_ = actionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.gruler.ResponseOuterClass.Response) {
          return mergeFrom((com.proto.gruler.ResponseOuterClass.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.gruler.ResponseOuterClass.Response other) {
        if (other == com.proto.gruler.ResponseOuterClass.Response.getDefaultInstance()) return this;
        if (other.getExecutionTime() != 0L) {
          setExecutionTime(other.getExecutionTime());
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (actionsBuilder_ == null) {
          if (!other.actions_.isEmpty()) {
            if (actions_.isEmpty()) {
              actions_ = other.actions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureActionsIsMutable();
              actions_.addAll(other.actions_);
            }
            onChanged();
          }
        } else {
          if (!other.actions_.isEmpty()) {
            if (actionsBuilder_.isEmpty()) {
              actionsBuilder_.dispose();
              actionsBuilder_ = null;
              actions_ = other.actions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              actionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getActionsFieldBuilder() : null;
            } else {
              actionsBuilder_.addAllMessages(other.actions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.gruler.ResponseOuterClass.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.gruler.ResponseOuterClass.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long executionTime_ ;
      /**
       * <code>int64 executionTime = 1;</code>
       * @return The executionTime.
       */
      @java.lang.Override
      public long getExecutionTime() {
        return executionTime_;
      }
      /**
       * <code>int64 executionTime = 1;</code>
       * @param value The executionTime to set.
       * @return This builder for chaining.
       */
      public Builder setExecutionTime(long value) {
        
        executionTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 executionTime = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearExecutionTime() {
        
        executionTime_ = 0L;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool success = 2;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool success = 2;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool success = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private java.util.List<com.proto.gruler.ResponseOuterClass.Action> actions_ =
        java.util.Collections.emptyList();
      private void ensureActionsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          actions_ = new java.util.ArrayList<com.proto.gruler.ResponseOuterClass.Action>(actions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.gruler.ResponseOuterClass.Action, com.proto.gruler.ResponseOuterClass.Action.Builder, com.proto.gruler.ResponseOuterClass.ActionOrBuilder> actionsBuilder_;

      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public java.util.List<com.proto.gruler.ResponseOuterClass.Action> getActionsList() {
        if (actionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(actions_);
        } else {
          return actionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public int getActionsCount() {
        if (actionsBuilder_ == null) {
          return actions_.size();
        } else {
          return actionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public com.proto.gruler.ResponseOuterClass.Action getActions(int index) {
        if (actionsBuilder_ == null) {
          return actions_.get(index);
        } else {
          return actionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder setActions(
          int index, com.proto.gruler.ResponseOuterClass.Action value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.set(index, value);
          onChanged();
        } else {
          actionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder setActions(
          int index, com.proto.gruler.ResponseOuterClass.Action.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.set(index, builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder addActions(com.proto.gruler.ResponseOuterClass.Action value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.add(value);
          onChanged();
        } else {
          actionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder addActions(
          int index, com.proto.gruler.ResponseOuterClass.Action value) {
        if (actionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureActionsIsMutable();
          actions_.add(index, value);
          onChanged();
        } else {
          actionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder addActions(
          com.proto.gruler.ResponseOuterClass.Action.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.add(builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder addActions(
          int index, com.proto.gruler.ResponseOuterClass.Action.Builder builderForValue) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.add(index, builderForValue.build());
          onChanged();
        } else {
          actionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder addAllActions(
          java.lang.Iterable<? extends com.proto.gruler.ResponseOuterClass.Action> values) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, actions_);
          onChanged();
        } else {
          actionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder clearActions() {
        if (actionsBuilder_ == null) {
          actions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          actionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public Builder removeActions(int index) {
        if (actionsBuilder_ == null) {
          ensureActionsIsMutable();
          actions_.remove(index);
          onChanged();
        } else {
          actionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public com.proto.gruler.ResponseOuterClass.Action.Builder getActionsBuilder(
          int index) {
        return getActionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public com.proto.gruler.ResponseOuterClass.ActionOrBuilder getActionsOrBuilder(
          int index) {
        if (actionsBuilder_ == null) {
          return actions_.get(index);  } else {
          return actionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public java.util.List<? extends com.proto.gruler.ResponseOuterClass.ActionOrBuilder> 
           getActionsOrBuilderList() {
        if (actionsBuilder_ != null) {
          return actionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(actions_);
        }
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public com.proto.gruler.ResponseOuterClass.Action.Builder addActionsBuilder() {
        return getActionsFieldBuilder().addBuilder(
            com.proto.gruler.ResponseOuterClass.Action.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public com.proto.gruler.ResponseOuterClass.Action.Builder addActionsBuilder(
          int index) {
        return getActionsFieldBuilder().addBuilder(
            index, com.proto.gruler.ResponseOuterClass.Action.getDefaultInstance());
      }
      /**
       * <code>repeated .proto.Action actions = 3;</code>
       */
      public java.util.List<com.proto.gruler.ResponseOuterClass.Action.Builder> 
           getActionsBuilderList() {
        return getActionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.proto.gruler.ResponseOuterClass.Action, com.proto.gruler.ResponseOuterClass.Action.Builder, com.proto.gruler.ResponseOuterClass.ActionOrBuilder> 
          getActionsFieldBuilder() {
        if (actionsBuilder_ == null) {
          actionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.proto.gruler.ResponseOuterClass.Action, com.proto.gruler.ResponseOuterClass.Action.Builder, com.proto.gruler.ResponseOuterClass.ActionOrBuilder>(
                  actions_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          actions_ = null;
        }
        return actionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Response)
    }

    // @@protoc_insertion_point(class_scope:proto.Response)
    private static final com.proto.gruler.ResponseOuterClass.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.gruler.ResponseOuterClass.Response();
    }

    public static com.proto.gruler.ResponseOuterClass.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.proto.gruler.ResponseOuterClass.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ActionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Action)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string actionType = 1;</code>
     * @return The actionType.
     */
    java.lang.String getActionType();
    /**
     * <code>string actionType = 1;</code>
     * @return The bytes for actionType.
     */
    com.google.protobuf.ByteString
        getActionTypeBytes();

    /**
     * <code>string ruleId = 2;</code>
     * @return The ruleId.
     */
    java.lang.String getRuleId();
    /**
     * <code>string ruleId = 2;</code>
     * @return The bytes for ruleId.
     */
    com.google.protobuf.ByteString
        getRuleIdBytes();

    /**
     * <code>int64 status = 3;</code>
     * @return The status.
     */
    long getStatus();

    /**
     * <code>string headerName = 4;</code>
     * @return The headerName.
     */
    java.lang.String getHeaderName();
    /**
     * <code>string headerName = 4;</code>
     * @return The bytes for headerName.
     */
    com.google.protobuf.ByteString
        getHeaderNameBytes();

    /**
     * <code>string headerValue = 5;</code>
     * @return The headerValue.
     */
    java.lang.String getHeaderValue();
    /**
     * <code>string headerValue = 5;</code>
     * @return The bytes for headerValue.
     */
    com.google.protobuf.ByteString
        getHeaderValueBytes();
  }
  /**
   * Protobuf type {@code proto.Action}
   */
  public static final class Action extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Action)
      ActionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Action.newBuilder() to construct.
    private Action(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Action() {
      actionType_ = "";
      ruleId_ = "";
      headerName_ = "";
      headerValue_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Action();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Action(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              actionType_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              ruleId_ = s;
              break;
            }
            case 24: {

              status_ = input.readInt64();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              headerName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              headerValue_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.proto.gruler.ResponseOuterClass.internal_static_proto_Action_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.proto.gruler.ResponseOuterClass.internal_static_proto_Action_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.proto.gruler.ResponseOuterClass.Action.class, com.proto.gruler.ResponseOuterClass.Action.Builder.class);
    }

    public static final int ACTIONTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object actionType_;
    /**
     * <code>string actionType = 1;</code>
     * @return The actionType.
     */
    @java.lang.Override
    public java.lang.String getActionType() {
      java.lang.Object ref = actionType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        actionType_ = s;
        return s;
      }
    }
    /**
     * <code>string actionType = 1;</code>
     * @return The bytes for actionType.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getActionTypeBytes() {
      java.lang.Object ref = actionType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        actionType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int RULEID_FIELD_NUMBER = 2;
    private volatile java.lang.Object ruleId_;
    /**
     * <code>string ruleId = 2;</code>
     * @return The ruleId.
     */
    @java.lang.Override
    public java.lang.String getRuleId() {
      java.lang.Object ref = ruleId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ruleId_ = s;
        return s;
      }
    }
    /**
     * <code>string ruleId = 2;</code>
     * @return The bytes for ruleId.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getRuleIdBytes() {
      java.lang.Object ref = ruleId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ruleId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 3;
    private long status_;
    /**
     * <code>int64 status = 3;</code>
     * @return The status.
     */
    @java.lang.Override
    public long getStatus() {
      return status_;
    }

    public static final int HEADERNAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object headerName_;
    /**
     * <code>string headerName = 4;</code>
     * @return The headerName.
     */
    @java.lang.Override
    public java.lang.String getHeaderName() {
      java.lang.Object ref = headerName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headerName_ = s;
        return s;
      }
    }
    /**
     * <code>string headerName = 4;</code>
     * @return The bytes for headerName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeaderNameBytes() {
      java.lang.Object ref = headerName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headerName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int HEADERVALUE_FIELD_NUMBER = 5;
    private volatile java.lang.Object headerValue_;
    /**
     * <code>string headerValue = 5;</code>
     * @return The headerValue.
     */
    @java.lang.Override
    public java.lang.String getHeaderValue() {
      java.lang.Object ref = headerValue_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        headerValue_ = s;
        return s;
      }
    }
    /**
     * <code>string headerValue = 5;</code>
     * @return The bytes for headerValue.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getHeaderValueBytes() {
      java.lang.Object ref = headerValue_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        headerValue_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActionTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, actionType_);
      }
      if (!getRuleIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, ruleId_);
      }
      if (status_ != 0L) {
        output.writeInt64(3, status_);
      }
      if (!getHeaderNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, headerName_);
      }
      if (!getHeaderValueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, headerValue_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActionTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, actionType_);
      }
      if (!getRuleIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, ruleId_);
      }
      if (status_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, status_);
      }
      if (!getHeaderNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, headerName_);
      }
      if (!getHeaderValueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, headerValue_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.proto.gruler.ResponseOuterClass.Action)) {
        return super.equals(obj);
      }
      com.proto.gruler.ResponseOuterClass.Action other = (com.proto.gruler.ResponseOuterClass.Action) obj;

      if (!getActionType()
          .equals(other.getActionType())) return false;
      if (!getRuleId()
          .equals(other.getRuleId())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getHeaderName()
          .equals(other.getHeaderName())) return false;
      if (!getHeaderValue()
          .equals(other.getHeaderValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTIONTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getActionType().hashCode();
      hash = (37 * hash) + RULEID_FIELD_NUMBER;
      hash = (53 * hash) + getRuleId().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatus());
      hash = (37 * hash) + HEADERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderName().hashCode();
      hash = (37 * hash) + HEADERVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getHeaderValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.proto.gruler.ResponseOuterClass.Action parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.proto.gruler.ResponseOuterClass.Action prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proto.Action}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Action)
        com.proto.gruler.ResponseOuterClass.ActionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.proto.gruler.ResponseOuterClass.internal_static_proto_Action_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.proto.gruler.ResponseOuterClass.internal_static_proto_Action_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.proto.gruler.ResponseOuterClass.Action.class, com.proto.gruler.ResponseOuterClass.Action.Builder.class);
      }

      // Construct using com.proto.gruler.ResponseOuterClass.Action.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        actionType_ = "";

        ruleId_ = "";

        status_ = 0L;

        headerName_ = "";

        headerValue_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.proto.gruler.ResponseOuterClass.internal_static_proto_Action_descriptor;
      }

      @java.lang.Override
      public com.proto.gruler.ResponseOuterClass.Action getDefaultInstanceForType() {
        return com.proto.gruler.ResponseOuterClass.Action.getDefaultInstance();
      }

      @java.lang.Override
      public com.proto.gruler.ResponseOuterClass.Action build() {
        com.proto.gruler.ResponseOuterClass.Action result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.proto.gruler.ResponseOuterClass.Action buildPartial() {
        com.proto.gruler.ResponseOuterClass.Action result = new com.proto.gruler.ResponseOuterClass.Action(this);
        result.actionType_ = actionType_;
        result.ruleId_ = ruleId_;
        result.status_ = status_;
        result.headerName_ = headerName_;
        result.headerValue_ = headerValue_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.proto.gruler.ResponseOuterClass.Action) {
          return mergeFrom((com.proto.gruler.ResponseOuterClass.Action)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.proto.gruler.ResponseOuterClass.Action other) {
        if (other == com.proto.gruler.ResponseOuterClass.Action.getDefaultInstance()) return this;
        if (!other.getActionType().isEmpty()) {
          actionType_ = other.actionType_;
          onChanged();
        }
        if (!other.getRuleId().isEmpty()) {
          ruleId_ = other.ruleId_;
          onChanged();
        }
        if (other.getStatus() != 0L) {
          setStatus(other.getStatus());
        }
        if (!other.getHeaderName().isEmpty()) {
          headerName_ = other.headerName_;
          onChanged();
        }
        if (!other.getHeaderValue().isEmpty()) {
          headerValue_ = other.headerValue_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.proto.gruler.ResponseOuterClass.Action parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.proto.gruler.ResponseOuterClass.Action) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object actionType_ = "";
      /**
       * <code>string actionType = 1;</code>
       * @return The actionType.
       */
      public java.lang.String getActionType() {
        java.lang.Object ref = actionType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          actionType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string actionType = 1;</code>
       * @return The bytes for actionType.
       */
      public com.google.protobuf.ByteString
          getActionTypeBytes() {
        java.lang.Object ref = actionType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          actionType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string actionType = 1;</code>
       * @param value The actionType to set.
       * @return This builder for chaining.
       */
      public Builder setActionType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        actionType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string actionType = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearActionType() {
        
        actionType_ = getDefaultInstance().getActionType();
        onChanged();
        return this;
      }
      /**
       * <code>string actionType = 1;</code>
       * @param value The bytes for actionType to set.
       * @return This builder for chaining.
       */
      public Builder setActionTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        actionType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object ruleId_ = "";
      /**
       * <code>string ruleId = 2;</code>
       * @return The ruleId.
       */
      public java.lang.String getRuleId() {
        java.lang.Object ref = ruleId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ruleId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string ruleId = 2;</code>
       * @return The bytes for ruleId.
       */
      public com.google.protobuf.ByteString
          getRuleIdBytes() {
        java.lang.Object ref = ruleId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ruleId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ruleId = 2;</code>
       * @param value The ruleId to set.
       * @return This builder for chaining.
       */
      public Builder setRuleId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ruleId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ruleId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearRuleId() {
        
        ruleId_ = getDefaultInstance().getRuleId();
        onChanged();
        return this;
      }
      /**
       * <code>string ruleId = 2;</code>
       * @param value The bytes for ruleId to set.
       * @return This builder for chaining.
       */
      public Builder setRuleIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ruleId_ = value;
        onChanged();
        return this;
      }

      private long status_ ;
      /**
       * <code>int64 status = 3;</code>
       * @return The status.
       */
      @java.lang.Override
      public long getStatus() {
        return status_;
      }
      /**
       * <code>int64 status = 3;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(long value) {
        
        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 status = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        
        status_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object headerName_ = "";
      /**
       * <code>string headerName = 4;</code>
       * @return The headerName.
       */
      public java.lang.String getHeaderName() {
        java.lang.Object ref = headerName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headerName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string headerName = 4;</code>
       * @return The bytes for headerName.
       */
      public com.google.protobuf.ByteString
          getHeaderNameBytes() {
        java.lang.Object ref = headerName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headerName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string headerName = 4;</code>
       * @param value The headerName to set.
       * @return This builder for chaining.
       */
      public Builder setHeaderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headerName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string headerName = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeaderName() {
        
        headerName_ = getDefaultInstance().getHeaderName();
        onChanged();
        return this;
      }
      /**
       * <code>string headerName = 4;</code>
       * @param value The bytes for headerName to set.
       * @return This builder for chaining.
       */
      public Builder setHeaderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headerName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object headerValue_ = "";
      /**
       * <code>string headerValue = 5;</code>
       * @return The headerValue.
       */
      public java.lang.String getHeaderValue() {
        java.lang.Object ref = headerValue_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          headerValue_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string headerValue = 5;</code>
       * @return The bytes for headerValue.
       */
      public com.google.protobuf.ByteString
          getHeaderValueBytes() {
        java.lang.Object ref = headerValue_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          headerValue_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string headerValue = 5;</code>
       * @param value The headerValue to set.
       * @return This builder for chaining.
       */
      public Builder setHeaderValue(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        headerValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string headerValue = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeaderValue() {
        
        headerValue_ = getDefaultInstance().getHeaderValue();
        onChanged();
        return this;
      }
      /**
       * <code>string headerValue = 5;</code>
       * @param value The bytes for headerValue to set.
       * @return This builder for chaining.
       */
      public Builder setHeaderValueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        headerValue_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Action)
    }

    // @@protoc_insertion_point(class_scope:proto.Action)
    private static final com.proto.gruler.ResponseOuterClass.Action DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.proto.gruler.ResponseOuterClass.Action();
    }

    public static com.proto.gruler.ResponseOuterClass.Action getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Action>
        PARSER = new com.google.protobuf.AbstractParser<Action>() {
      @java.lang.Override
      public Action parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Action(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Action> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Action> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.proto.gruler.ResponseOuterClass.Action getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Response_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Action_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Action_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030pkg/proto/response.proto\022\005proto\"R\n\010Res" +
      "ponse\022\025\n\rexecutionTime\030\001 \001(\003\022\017\n\007success\030" +
      "\002 \001(\010\022\036\n\007actions\030\003 \003(\0132\r.proto.Action\"e\n" +
      "\006Action\022\022\n\nactionType\030\001 \001(\t\022\016\n\006ruleId\030\002 " +
      "\001(\t\022\016\n\006status\030\003 \001(\003\022\022\n\nheaderName\030\004 \001(\t\022" +
      "\023\n\013headerValue\030\005 \001(\tB$\n\020com.proto.gruler" +
      "Z\020gruler/pkg/protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proto_Response_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Response_descriptor,
        new java.lang.String[] { "ExecutionTime", "Success", "Actions", });
    internal_static_proto_Action_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_Action_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Action_descriptor,
        new java.lang.String[] { "ActionType", "RuleId", "Status", "HeaderName", "HeaderValue", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
