name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
        
    - name: Protoc action
      uses: PxyUp/protoc-actions@v2.0.9

    - name: Build
      run: make all

    - name: Test
      run: go test -v ./...
